run_configs:
- agent_ids:
  - agent_76c3950c
  config_id: rc_13608527
  created_at: '2026-04-07T20:12:38.842708'
  name: Ping test
  suite_types:
  - functional
  tags: []
- agent_ids:
  - agent_76c3950c
  config_id: rc_ab4723ef
  created_at: '2026-04-07T20:28:40.029128'
  name: Securotuy
  suite_types:
  - security
  tags: []
